/** 全站布局/灰阶令牌(微信式信息架构 × Claude 暖调色,U7 换肤只换值不换键)。 */
export const wechat = {
  pageBg: '#FAF9F5',
  cellBg: '#FFFFFF',
  navBg: '#FAF9F5',
  navBorder: '#E3E1D7',
  separator: '#EAE8DF',
  separatorInset: 16,
  separatorInsetWithAvatar: 68,
  textPrimary: '#1F1E1D',
  textSecondary: '#6E6B64',
  textTertiary: '#A8A69E',
  groupGap: 10,
  rowMinHeight: 56,
  rowMinHeightWithSubtitle: 72,
  searchBg: '#FFFFFF',
  cellRadius: 0,
  cardRadius: 8,
  navBarHeight: 44,
  navTitleSize: 17,
  listTitleSize: 17,
  listSubtitleSize: 14,
  listTimeSize: 12,
  footerHintSize: 13,
  avatarSize: 36,
  avatarRadius: 4,
  bubbleSelf: '#F1E0D4',
  bubbleOther: '#FFFFFF',
  bubbleText: '#1F1E1D',
  timeLabel: '#A8A69E',
  senderName: '#87857C',
  bubbleRadius: 4,
  bubblePadH: 10,
  bubblePadV: 6,
  chatFontSize: 15,
  chatLineHeight: 20,
  bubbleMaxWidth: '70%' as const,
  aiBubbleMaxWidth: '96%' as const,
} as const;

/** @deprecated 使用 wechat；保留别名兼容聊天模块 */
export const wechatChat = wechat;
