/** 微信式布局令牌（全站列表/设置/导航） */
export const wechat = {
  pageBg: '#EDEDED',
  cellBg: '#FFFFFF',
  navBg: '#F7F7F7',
  navBorder: '#D9D9D9',
  separator: '#E5E5E5',
  separatorInset: 16,
  separatorInsetWithAvatar: 68,
  textPrimary: '#191919',
  textSecondary: '#999999',
  textTertiary: '#B2B2B2',
  groupGap: 10,
  rowMinHeight: 56,
  rowMinHeightWithSubtitle: 72,
  searchBg: '#FFFFFF',
  cellRadius: 0,
  cardRadius: 8,
  navBarHeight: 44,
  navTitleSize: 17,
  listTitleSize: 17,
  listSubtitleSize: 14,
  listTimeSize: 12,
  footerHintSize: 13,
  avatarSize: 36,
  avatarRadius: 4,
  bubbleSelf: '#95EC69',
  bubbleOther: '#FFFFFF',
  bubbleText: '#000000',
  timeLabel: '#B2B2B2',
  senderName: '#888888',
  bubbleRadius: 4,
  bubblePadH: 10,
  bubblePadV: 6,
  chatFontSize: 15,
  chatLineHeight: 20,
  bubbleMaxWidth: '70%' as const,
  aiBubbleMaxWidth: '96%' as const,
} as const;

/** @deprecated 使用 wechat；保留别名兼容聊天模块 */
export const wechatChat = wechat;
